/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.farm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFarmScopeProvider extends DelegatingScopeProvider {
}
