/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.BoolLiteral#isVal <em>Val</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getBoolLiteral()
 * @model
 * @generated
 */
public interface BoolLiteral extends BooleanLiteral
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(boolean)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getBoolLiteral_Val()
   * @model
   * @generated
   */
  boolean isVal();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.BoolLiteral#isVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #isVal()
   * @generated
   */
  void setVal(boolean value);

} // BoolLiteral
