/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends EObject
{
} // Class
