/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.ComparisonExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.ComparisonExpression#getOperator <em>Operator</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.ComparisonExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getComparisonExpression()
 * @model
 * @generated
 */
public interface ComparisonExpression extends ConditionExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ConditionExpression)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getComparisonExpression_Left()
   * @model containment="true"
   * @generated
   */
  ConditionExpression getLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.ComparisonExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ConditionExpression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getComparisonExpression_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.ComparisonExpression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ConditionExpression)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getComparisonExpression_Right()
   * @model containment="true"
   * @generated
   */
  ConditionExpression getRight();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.ComparisonExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ConditionExpression value);

} // ComparisonExpression
