/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Count Stage Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.CountStageFunction#getCountStageCrop <em>Count Stage Crop</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getCountStageFunction()
 * @model
 * @generated
 */
public interface CountStageFunction extends BuiltinFunction
{
  /**
   * Returns the value of the '<em><b>Count Stage Crop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count Stage Crop</em>' reference.
   * @see #setCountStageCrop(Crop)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCountStageFunction_CountStageCrop()
   * @model
   * @generated
   */
  Crop getCountStageCrop();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.CountStageFunction#getCountStageCrop <em>Count Stage Crop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count Stage Crop</em>' reference.
   * @see #getCountStageCrop()
   * @generated
   */
  void setCountStageCrop(Crop value);

} // CountStageFunction
