/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crop Stage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.CropStage#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.CropStage#getTimeConsumend <em>Time Consumend</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.CropStage#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getCropStage()
 * @model
 * @generated
 */
public interface CropStage extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCropStage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.CropStage#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Time Consumend</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Consumend</em>' containment reference.
   * @see #setTimeConsumend(RealExpression)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCropStage_TimeConsumend()
   * @model containment="true"
   * @generated
   */
  RealExpression getTimeConsumend();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.CropStage#getTimeConsumend <em>Time Consumend</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Consumend</em>' containment reference.
   * @see #getTimeConsumend()
   * @generated
   */
  void setTimeConsumend(RealExpression value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.farm.farm.CropAttributes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCropStage_Elements()
   * @model containment="true"
   * @generated
   */
  EList<CropAttributes> getElements();

} // CropStage
