/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Crop Attributes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.CropAttributes#getType <em>Type</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.CropAttributes#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getCropAttributes()
 * @model
 * @generated
 */
public interface CropAttributes extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(AttributeDeclaration)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCropAttributes_Type()
   * @model
   * @generated
   */
  AttributeDeclaration getType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.CropAttributes#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(AttributeDeclaration value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(RealExpression)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getCropAttributes_Value()
   * @model containment="true"
   * @generated
   */
  RealExpression getValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.CropAttributes#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(RealExpression value);

} // CropAttributes
