/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends ExpressionOrCall
{
} // Expression
