/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Monitor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.FieldMonitor#getMonitor <em>Monitor</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getFieldMonitor()
 * @model
 * @generated
 */
public interface FieldMonitor extends EObject
{
  /**
   * Returns the value of the '<em><b>Monitor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monitor</em>' reference.
   * @see #setMonitor(Attribute)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getFieldMonitor_Monitor()
   * @model
   * @generated
   */
  Attribute getMonitor();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.FieldMonitor#getMonitor <em>Monitor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monitor</em>' reference.
   * @see #getMonitor()
   * @generated
   */
  void setMonitor(Attribute value);

} // FieldMonitor
