/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get Stage Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.GetStageFunction#getGetStageCrop <em>Get Stage Crop</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.GetStageFunction#getStageNumber <em>Stage Number</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getGetStageFunction()
 * @model
 * @generated
 */
public interface GetStageFunction extends BuiltinFunction
{
  /**
   * Returns the value of the '<em><b>Get Stage Crop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Get Stage Crop</em>' reference.
   * @see #setGetStageCrop(Crop)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getGetStageFunction_GetStageCrop()
   * @model
   * @generated
   */
  Crop getGetStageCrop();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.GetStageFunction#getGetStageCrop <em>Get Stage Crop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Get Stage Crop</em>' reference.
   * @see #getGetStageCrop()
   * @generated
   */
  void setGetStageCrop(Crop value);

  /**
   * Returns the value of the '<em><b>Stage Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stage Number</em>' attribute.
   * @see #setStageNumber(int)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getGetStageFunction_StageNumber()
   * @model
   * @generated
   */
  int getStageNumber();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.GetStageFunction#getStageNumber <em>Stage Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stage Number</em>' attribute.
   * @see #getStageNumber()
   * @generated
   */
  void setStageNumber(int value);

} // GetStageFunction
