/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.farm.farm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getIntExpression()
 * @model
 * @generated
 */
public interface IntExpression extends EObject
{
} // IntExpression
