/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends Expression
{
} // Literal
