/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plant Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.PlantFunction#getPlantInField <em>Plant In Field</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.PlantFunction#getPlantCrop <em>Plant Crop</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getPlantFunction()
 * @model
 * @generated
 */
public interface PlantFunction extends BuiltinFunction
{
  /**
   * Returns the value of the '<em><b>Plant In Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plant In Field</em>' reference.
   * @see #setPlantInField(Field)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getPlantFunction_PlantInField()
   * @model
   * @generated
   */
  Field getPlantInField();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.PlantFunction#getPlantInField <em>Plant In Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plant In Field</em>' reference.
   * @see #getPlantInField()
   * @generated
   */
  void setPlantInField(Field value);

  /**
   * Returns the value of the '<em><b>Plant Crop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plant Crop</em>' reference.
   * @see #setPlantCrop(Crop)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getPlantFunction_PlantCrop()
   * @model
   * @generated
   */
  Crop getPlantCrop();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.PlantFunction#getPlantCrop <em>Plant Crop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plant Crop</em>' reference.
   * @see #getPlantCrop()
   * @generated
   */
  void setPlantCrop(Crop value);

} // PlantFunction
