/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Report Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.ReportFunction#getReportCrop <em>Report Crop</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.ReportFunction#getReportField <em>Report Field</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.farm.farm.FarmPackage#getReportFunction()
 * @model
 * @generated
 */
public interface ReportFunction extends BuiltinFunction
{
  /**
   * Returns the value of the '<em><b>Report Crop</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Report Crop</em>' reference.
   * @see #setReportCrop(Crop)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getReportFunction_ReportCrop()
   * @model
   * @generated
   */
  Crop getReportCrop();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.ReportFunction#getReportCrop <em>Report Crop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Report Crop</em>' reference.
   * @see #getReportCrop()
   * @generated
   */
  void setReportCrop(Crop value);

  /**
   * Returns the value of the '<em><b>Report Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Report Field</em>' reference.
   * @see #setReportField(Field)
   * @see uk.ac.kcl.farm.farm.FarmPackage#getReportFunction_ReportField()
   * @model
   * @generated
   */
  Field getReportField();

  /**
   * Sets the value of the '{@link uk.ac.kcl.farm.farm.ReportFunction#getReportField <em>Report Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Report Field</em>' reference.
   * @see #getReportField()
   * @generated
   */
  void setReportField(Field value);

} // ReportFunction
