/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.farm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.farm.FarmRuntimeModule;
import uk.ac.kcl.farm.FarmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FarmIdeSetup extends FarmStandaloneSetup {
  @Override
  public Injector createInjector() {
    FarmRuntimeModule _farmRuntimeModule = new FarmRuntimeModule();
    FarmIdeModule _farmIdeModule = new FarmIdeModule();
    return Guice.createInjector(Modules2.mixin(_farmRuntimeModule, _farmIdeModule));
  }
}
