/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.farm.farm.FarmPackage;
import uk.ac.kcl.farm.farm.Field;
import uk.ac.kcl.farm.farm.GetFieldValueFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Get Field Value Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.GetFieldValueFunctionImpl#getGetValueField <em>Get Value Field</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.GetFieldValueFunctionImpl#getGetFieldAttribute <em>Get Field Attribute</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GetFieldValueFunctionImpl extends BuiltinFunctionImpl implements GetFieldValueFunction
{
  /**
   * The cached value of the '{@link #getGetValueField() <em>Get Value Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGetValueField()
   * @generated
   * @ordered
   */
  protected Field getValueField;

  /**
   * The default value of the '{@link #getGetFieldAttribute() <em>Get Field Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGetFieldAttribute()
   * @generated
   * @ordered
   */
  protected static final String GET_FIELD_ATTRIBUTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGetFieldAttribute() <em>Get Field Attribute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGetFieldAttribute()
   * @generated
   * @ordered
   */
  protected String getFieldAttribute = GET_FIELD_ATTRIBUTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GetFieldValueFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FarmPackage.Literals.GET_FIELD_VALUE_FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field getGetValueField()
  {
    if (getValueField != null && getValueField.eIsProxy())
    {
      InternalEObject oldGetValueField = (InternalEObject)getValueField;
      getValueField = (Field)eResolveProxy(oldGetValueField);
      if (getValueField != oldGetValueField)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD, oldGetValueField, getValueField));
      }
    }
    return getValueField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field basicGetGetValueField()
  {
    return getValueField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGetValueField(Field newGetValueField)
  {
    Field oldGetValueField = getValueField;
    getValueField = newGetValueField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD, oldGetValueField, getValueField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGetFieldAttribute()
  {
    return getFieldAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGetFieldAttribute(String newGetFieldAttribute)
  {
    String oldGetFieldAttribute = getFieldAttribute;
    getFieldAttribute = newGetFieldAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_FIELD_ATTRIBUTE, oldGetFieldAttribute, getFieldAttribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD:
        if (resolve) return getGetValueField();
        return basicGetGetValueField();
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_FIELD_ATTRIBUTE:
        return getGetFieldAttribute();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD:
        setGetValueField((Field)newValue);
        return;
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_FIELD_ATTRIBUTE:
        setGetFieldAttribute((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD:
        setGetValueField((Field)null);
        return;
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_FIELD_ATTRIBUTE:
        setGetFieldAttribute(GET_FIELD_ATTRIBUTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_VALUE_FIELD:
        return getValueField != null;
      case FarmPackage.GET_FIELD_VALUE_FUNCTION__GET_FIELD_ATTRIBUTE:
        return GET_FIELD_ATTRIBUTE_EDEFAULT == null ? getFieldAttribute != null : !GET_FIELD_ATTRIBUTE_EDEFAULT.equals(getFieldAttribute);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (getFieldAttribute: ");
    result.append(getFieldAttribute);
    result.append(')');
    return result.toString();
  }

} //GetFieldValueFunctionImpl
