/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.farm.farm.Crop;
import uk.ac.kcl.farm.farm.FarmPackage;
import uk.ac.kcl.farm.farm.GetStageFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Get Stage Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.GetStageFunctionImpl#getGetStageCrop <em>Get Stage Crop</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.GetStageFunctionImpl#getStageNumber <em>Stage Number</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GetStageFunctionImpl extends BuiltinFunctionImpl implements GetStageFunction
{
  /**
   * The cached value of the '{@link #getGetStageCrop() <em>Get Stage Crop</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGetStageCrop()
   * @generated
   * @ordered
   */
  protected Crop getStageCrop;

  /**
   * The default value of the '{@link #getStageNumber() <em>Stage Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStageNumber()
   * @generated
   * @ordered
   */
  protected static final int STAGE_NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStageNumber() <em>Stage Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStageNumber()
   * @generated
   * @ordered
   */
  protected int stageNumber = STAGE_NUMBER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GetStageFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FarmPackage.Literals.GET_STAGE_FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Crop getGetStageCrop()
  {
    if (getStageCrop != null && getStageCrop.eIsProxy())
    {
      InternalEObject oldGetStageCrop = (InternalEObject)getStageCrop;
      getStageCrop = (Crop)eResolveProxy(oldGetStageCrop);
      if (getStageCrop != oldGetStageCrop)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP, oldGetStageCrop, getStageCrop));
      }
    }
    return getStageCrop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Crop basicGetGetStageCrop()
  {
    return getStageCrop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGetStageCrop(Crop newGetStageCrop)
  {
    Crop oldGetStageCrop = getStageCrop;
    getStageCrop = newGetStageCrop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP, oldGetStageCrop, getStageCrop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getStageNumber()
  {
    return stageNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStageNumber(int newStageNumber)
  {
    int oldStageNumber = stageNumber;
    stageNumber = newStageNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.GET_STAGE_FUNCTION__STAGE_NUMBER, oldStageNumber, stageNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP:
        if (resolve) return getGetStageCrop();
        return basicGetGetStageCrop();
      case FarmPackage.GET_STAGE_FUNCTION__STAGE_NUMBER:
        return getStageNumber();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP:
        setGetStageCrop((Crop)newValue);
        return;
      case FarmPackage.GET_STAGE_FUNCTION__STAGE_NUMBER:
        setStageNumber((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP:
        setGetStageCrop((Crop)null);
        return;
      case FarmPackage.GET_STAGE_FUNCTION__STAGE_NUMBER:
        setStageNumber(STAGE_NUMBER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.GET_STAGE_FUNCTION__GET_STAGE_CROP:
        return getStageCrop != null;
      case FarmPackage.GET_STAGE_FUNCTION__STAGE_NUMBER:
        return stageNumber != STAGE_NUMBER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (stageNumber: ");
    result.append(stageNumber);
    result.append(')');
    return result.toString();
  }

} //GetStageFunctionImpl
