/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.farm.farm.FarmPackage;
import uk.ac.kcl.farm.farm.Field;
import uk.ac.kcl.farm.farm.MoveFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.MoveFunctionImpl#getMoveFromField <em>Move From Field</em>}</li>
 *   <li>{@link uk.ac.kcl.farm.farm.impl.MoveFunctionImpl#getMoveToField <em>Move To Field</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MoveFunctionImpl extends BuiltinFunctionImpl implements MoveFunction
{
  /**
   * The cached value of the '{@link #getMoveFromField() <em>Move From Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoveFromField()
   * @generated
   * @ordered
   */
  protected Field moveFromField;

  /**
   * The cached value of the '{@link #getMoveToField() <em>Move To Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoveToField()
   * @generated
   * @ordered
   */
  protected Field moveToField;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FarmPackage.Literals.MOVE_FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field getMoveFromField()
  {
    if (moveFromField != null && moveFromField.eIsProxy())
    {
      InternalEObject oldMoveFromField = (InternalEObject)moveFromField;
      moveFromField = (Field)eResolveProxy(oldMoveFromField);
      if (moveFromField != oldMoveFromField)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD, oldMoveFromField, moveFromField));
      }
    }
    return moveFromField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field basicGetMoveFromField()
  {
    return moveFromField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMoveFromField(Field newMoveFromField)
  {
    Field oldMoveFromField = moveFromField;
    moveFromField = newMoveFromField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD, oldMoveFromField, moveFromField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field getMoveToField()
  {
    if (moveToField != null && moveToField.eIsProxy())
    {
      InternalEObject oldMoveToField = (InternalEObject)moveToField;
      moveToField = (Field)eResolveProxy(oldMoveToField);
      if (moveToField != oldMoveToField)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD, oldMoveToField, moveToField));
      }
    }
    return moveToField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Field basicGetMoveToField()
  {
    return moveToField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMoveToField(Field newMoveToField)
  {
    Field oldMoveToField = moveToField;
    moveToField = newMoveToField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD, oldMoveToField, moveToField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD:
        if (resolve) return getMoveFromField();
        return basicGetMoveFromField();
      case FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD:
        if (resolve) return getMoveToField();
        return basicGetMoveToField();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD:
        setMoveFromField((Field)newValue);
        return;
      case FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD:
        setMoveToField((Field)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD:
        setMoveFromField((Field)null);
        return;
      case FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD:
        setMoveToField((Field)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FarmPackage.MOVE_FUNCTION__MOVE_FROM_FIELD:
        return moveFromField != null;
      case FarmPackage.MOVE_FUNCTION__MOVE_TO_FIELD:
        return moveToField != null;
    }
    return super.eIsSet(featureID);
  }

} //MoveFunctionImpl
