/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.farm.farm.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.farm.farm.FarmPackage;
import uk.ac.kcl.farm.farm.RealExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Real Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RealExpressionImpl extends VariableExpressionImpl implements RealExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RealExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FarmPackage.Literals.REAL_EXPRESSION;
  }

} //RealExpressionImpl
